### ISSUE TITLE
说实话怎么使用没有看明白

### ISSUE THREAD

**Issue by toKnowMore** [message163/tracker#1]
requestUrl是后台接口地址吗?

那defaultOptions中的其他数据又是怎么传输的呢?

**Comment by toKnowMore** [comment]
我看到core.ts 中 reportTracker方法,如果自定义请求头是不是这个方法需要修改

**Comment by toKnowMore** [comment]
我明白了,这个实际需要根据自己的需求进行稍微改动

**Comment by message163** [comment]
目前 sendBeacon 不支持 json 请求头 传输 数据只能用blob 代替

**Comment by toKnowMore** [comment]
那么触发时机是什么?什么时候该传输数据呢?

**Comment by toKnowMore** [comment]
难道是每一次的路由变化或者点击事件手动触发

**Comment by message163** [comment]
如果开启 history模式 变化会自动上报  hash 亦是如此     开启domTracker  你可以给你需要上报的按钮增加 target-key="埋点值"  会自动上报

**Comment by toKnowMore** [comment]
好的,明白了,多谢

**Comment by message163** [comment]
我把REANME 补充一下吧
